#!/bin/bash

n=$(git config user.name)
if [ -z "$n" ]; then
    n="NONE"
fi

e=$(git config user.email)
if [ -z "$e" ]; then
    e="NONE"
fi

s=$(git config user.signingkey)
if [ -z "$s" ]; then
    s="NONE"
fi

r=$(osascript -e '
tell application "System Events"
    set frontApp to name of first application process whose frontmost is true
end tell
tell application "System Events"
    set r to display dialog "'"Текущий пользователь GIT\n\nname: $n\nemail: $e\nsigningkey: $s"'" buttons {"Продолжить", "Отмена"} default button "Продолжить"
end tell
tell application frontApp to activate
return r
')
if [ "$r" = "button returned:Продолжить" ]; then
    echo "Подтверждение текущего пользователя GIT"
else
   exit 1;
fi
